Web/Controllers/WorkplaceController.cs
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using DataContext.Data;
using DataContext.Model;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Web.Authentication;
using Web.Models;
using Web.ViewModels;

namespace Web.Controllers
{
    [Authorize]
    public class WorkplaceController : Controller
    {
        private readonly FilmExperienceContext _context;
        private readonly Microsoft.AspNetCore.Identity.UserManager<Employee> _userManager;

        public WorkplaceController(FilmExperienceContext context,
            Microsoft.AspNetCore.Identity.UserManager<Employee> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var user = _userManager.GetUserAsync(HttpContext.User).Result;

            var model = new WorkplaceModel
            {
                Workplaces = _context.Workplace.Where(x => x.Employee.EmployeeNumber == user.EmployeeNumber).ToList()
            };

            return View(model);
        }

         
        [HttpGet]
        public IActionResult Edit(int employeeNumber)
        {
            var model = new ManageEmployeeModel
            {
                Employee = _context.Employee.Single(x => x.EmployeeNumber == employeeNumber)
            };
            
            return View(model);
        }
        
        public IActionResult Update(int employeeNumber, Employee employee)
        {
            var persistedEmployee = _context.Employee.Single(x => x.EmployeeNumber == employeeNumber);

            persistedEmployee.Email = employee.Email;

            _context.Update(persistedEmployee);

            return RedirectToAction("Index", "Employee");
        }

        public IActionResult Delete()
        {
            var model = new EmployeeModel
            {
                Employees = _context.Employee.ToList()
            };

            return RedirectToAction("Index", "Employee");
        }
    }
}

Web/Views/Workplace/Edit.cshtml
@model Web.ViewModels.ManageEmployeeModel

<div class="row">
    <h1>Edit</h1>

    <form asp-controller="Employee" asp-action="Update" method="post">
        <input type="email" name="Email" value="@Model.Employee.Email"/>
        <input type="password" name="Password"/>
    </form>
</div>

Web/Views/Workplace/index.cshtml
@model Web.ViewModels.WorkplaceModel

<div class="row">
    <h1>Employees</h1>
    <table class="table table-bordered">
        <tr>
            <th>#</th>
            <th>Edit</th>
            <th>Remove</th>
        </tr>
        @foreach (var workplace in Model.Workplaces)
        {
            <tr>
                <td>@workplace.WorkplaceName</td>
                <td>
                    <a asp-area="" asp-controller="Workplace" asp-action="Edit" asp-route-employeeNumber="@workplace.WorkplaceNumber">Edit</a>
                </td>
                <td>
                    <a asp-area="" asp-controller="Workplace" asp-action="Delete">Remove</a>
                </td>
            </tr>
        }
    </table>
</div>